import 'package:flutter/material.dart';

class AppColors {
  static const bg = Color(0xFFFFF0F6);
  static const nodeLocked = Color(0xFFBDBDBD);
  static const nodeUnlocked = Color(0xFFFFC1E3);
}

class Strings {
  static const en = {
    'map_title': 'Map',
    'shop_title': 'Shop',
    'start': 'Level',
    'coins': 'Coins',
    'stars': 'Stars',
    'freeze': 'Freeze Time activated for 20s!',
    'double': 'Double Coins for next 3 plays',
    'time_up': 'Time up!',
    'level_complete': 'Level complete',
    'buy': 'Buy',
    'purchased': 'Purchased',
    'not_enough_coins': 'Not enough coins',
    'freeze_time': 'Freeze Time',
    'double_coins': 'Double Coins for next 3 plays',
    'owned': 'Owned',
    'back': 'Back',
    'freeze_used': 'Freeze Time activated for 20s!',
    'double_used': 'Double Coins for next 3 plays!',
    'max_freeze': 'Max 5 freezes per level!',
    'dropped_pieces': 'Dropped pieces:',
    'milestone_reward': '⭐ SPECIAL REWARD ⭐',
    'better_luck': 'Better luck next time!',
    'level_failed': 'You did not complete this level.',
    'theme_default': 'Default',
    'theme_emoji': 'Emoji',
    'theme_fruits': 'Fruits & Vegetables',
    'theme_food': 'Food',
    'shop_items_title': 'Items',
    'shop_themes_title': 'Themes',
    'stars_required': 'Stars Required',
    'selected': 'Selected',
    'select': 'Select',
    'unlock': 'Unlock',
    'unlocked': 'Unlocked',
    'change_language': 'Change Language',
    'view_shop': 'View Shop',
    'view_puzzles': 'View Puzzles',
    'puzzle_gallery_title': 'Puzzle Gallery',
    'puzzle_complete': 'Puzzle Complete!',
    'not_enough_items': 'Not enough items!',
    'freeze_already_active': 'Freeze is already active!',
    'double_already_active': 'Double Coins already active!',
    'plays_left': 'Plays left',
    'ok': 'OK',
    'item_freeze': 'Freeze',
    'item_double': 'Double',
    'loading_game_data': 'Loading game data...',
    'level_locked': 'Level is locked',
    'no_puzzle_pieces': 'You have no piece for this puzzle yet!',
    'switched_theme': 'Switched theme',
    'unlock_failed': 'Failed to unlock',
    'intro_desc_1':
        'Welcome to Card Saga – the world of magical cards and colorful puzzle pieces!',
    'intro_desc_2':
        'Get ready for a journey to explore, train your memory, and complete adorable pictures!',
    'team_title': 'Development Team',
    'member_1': 'Nguyễn Ngọc Linh',
    'member_2': 'Vũ Thị Trang',
    'loading': 'Loading...',
    'play': 'PLAY!',
  };

  static const vi = {
    'map_title': 'Bản đồ',
    'shop_title': 'Cửa hàng',
    'start': 'Màn',
    'coins': 'Xu',
    'stars': 'Sao',
    'freeze': 'Đóng băng thời gian trong 20s!',
    'double': 'Nhân đôi xu trong 3 lượt chơi tiếp theo!',
    'time_up': 'Hết thời gian!',
    'level_complete': 'Hoàn thành ải',
    'buy': 'Mua',
    'purchased': 'Đã mua',
    'not_enough_coins': 'Không đủ xu',
    'freeze_time': 'Đóng băng thời gian',
    'double_coins': 'Nhân đôi xu trong 3 lượt chơi tiếp theo',
    'owned': 'Sở hữu',
    'back': 'Quay lại',
    'freeze_used': 'Đã kích hoạt Đóng băng thời gian trong 20 giây!',
    'double_used': 'Đã kích hoạt Nhân đôi Xu trong 3 lượt tới!',
    'max_freeze': 'Mỗi màn chỉ dùng tối đa 5 lần Đóng băng!',
    'dropped_pieces': 'Mảnh thu được:',
    'milestone_reward': '⭐ PHẦN THƯỞNG ĐẶC BIỆT ⭐',
    'better_luck': 'Chúc bạn may mắn lần sau!',
    'level_failed': 'Bạn đã không hoàn thành ải này.',
    'theme_default': 'Mặc định',
    'theme_emoji': 'Biểu cảm',
    'theme_fruits': 'Trái cây & Rau củ',
    'theme_food': 'Món ăn',
    'shop_items_title': 'Vật phẩm',
    'shop_themes_title': 'Chủ đề',
    'stars_required': 'Số sao cần thu thập',
    'selected': 'Đã chọn',
    'select': 'Chọn',
    'unlock': 'Mở khóa',
    'unlocked': 'Đã mở khóa',
    'change_language': 'Đổi Ngôn Ngữ',
    'view_shop': 'Xem Cửa Hàng',
    'view_puzzles': 'Xem Tranh Ghép',
    'puzzle_gallery_title': 'Bộ sưu tập Tranh',
    'puzzle_complete': 'Đã hoàn thành tranh!',
    'not_enough_items': 'Không đủ vật phẩm!',
    'freeze_already_active': 'Đóng băng đã được kích hoạt!',
    'double_already_active': 'Nhân đôi Xu đã được kích hoạt!',
    'plays_left': 'Lượt sử dụng còn lại',
    'ok': 'OK',
    'item_freeze': 'Đóng băng',
    'item_double': 'Nhân đôi',
    'loading_game_data': 'Đang tải dữ liệu game...',
    'level_locked': 'Màn chơi đã bị khóa',
    'no_puzzle_pieces': 'Bạn chưa có mảnh ghép nào cho tranh này!',
    'switched_theme': 'Đã đổi chủ đề',
    'unlock_failed': 'Mở khóa thất bại',
    'intro_desc_1':
        'Chào mừng đến với Card Saga – thế giới của những thẻ bài kỳ diệu và mảnh ghép đầy sắc màu!',
    'intro_desc_2':
        'Hãy sẵn sàng cho hành trình khám phá, rèn luyện trí nhớ và hoàn thành những bức tranh đáng yêu nhé!',
    'team_title': 'Nhóm phát triển',
    'member_1': 'Nguyễn Ngọc Linh',
    'member_2': 'Vũ Thị Trang',
    'loading': 'Đang tải...',
    'play': 'CHƠI!',
    'switched_to': 'Chuyển sang'
  };
}
